# Generated by Django 3.0.1 on 2020-02-25 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BooksInformation',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=100)),
                ('book_author_name', models.CharField(max_length=100)),
                ('book_description', models.CharField(max_length=500)),
                ('book_path', models.CharField(max_length=500)),
                ('book_upload_date', models.DateField(auto_now=True)),
                ('book_owner_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TheShelf.User')),
            ],
        ),
    ]
