# Generated by Django 3.0.1 on 2020-03-12 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TheShelf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksinformation',
            name='book_cover',
            field=models.FileField(default=django.utils.timezone.now, upload_to='BooksPdf'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booksinformation',
            name='book_path',
            field=models.ImageField(upload_to='BooksCoverPhoto'),
        ),
    ]
