# Generated by Django 3.0.1 on 2020-03-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheShelf', '0002_auto_20200312_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksinformation',
            name='book_cover',
            field=models.ImageField(upload_to='BooksCoverPhoto'),
        ),
        migrations.AlterField(
            model_name='booksinformation',
            name='book_path',
            field=models.FileField(upload_to='BooksPdf'),
        ),
    ]
