# Generated by Django 3.0.1 on 2020-03-13 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TheShelf', '0003_auto_20200312_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksinformation',
            name='book_catagory',
            field=models.CharField(default='Undefined', max_length=100),
        ),
        migrations.AlterField(
            model_name='booksinformation',
            name='book_owner_user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='TheShelf.User'),
        ),
    ]
