# Generated by Django 3.0.1 on 2020-03-13 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TheShelf', '0004_auto_20200313_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksinformation',
            name='book_owner_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TheShelf.User'),
        ),
    ]
