# Generated by Django 3.0.1 on 2020-04-21 17:18

import TheShelf.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheShelf', '0005_auto_20200313_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booksinformation',
            name='book_cover',
            field=models.ImageField(upload_to=TheShelf.models.coverdirname),
        ),
        migrations.AlterField(
            model_name='booksinformation',
            name='book_path',
            field=models.FileField(upload_to=TheShelf.models.bookdirname),
        ),
    ]
