# Generated by Django 3.0.1 on 2020-04-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheShelf', '0006_auto_20200421_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_default',
            field=models.BooleanField(default=True),
        ),
    ]
