# Generated by Django 3.0.1 on 2020-05-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheShelf', '0007_auto_20200427_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksinformation',
            name='book_author_name',
            field=models.CharField(default='Undefined', max_length=100),
        ),
        migrations.AlterField(
            model_name='booksinformation',
            name='book_description',
            field=models.CharField(default='Undefined', max_length=500),
        ),
        migrations.AlterField(
            model_name='booksinformation',
            name='book_name',
            field=models.CharField(default='Undefined', max_length=100),
        ),
    ]
